# Generated by Django 3.2 on 2023-02-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originalapp', '0002_alter_customuser_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='document/'),
        ),
    ]
